version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: clone-e2e-test
          command: git clone https://github.com/contentful/the-example-app-e2e-tests.git ./test/e2e
      - run:
          name: install-e2e-test
          command: cd ./test/e2e && npm install
      - run:
          name: running deployment
          command: curl -u veekrum:11fb0ed52d92e0385d3ab9d22b1256b115 http://167.71.244.101:8080/view/QA/job/QA-cicd_deploy_demo/build?token=wefiytgwiefiweihfqweiodf



