## the-example-app.nodejs
version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependency
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: clone the project
          command: git clone https://github.com/contentful/the-example-app-e2e-tests.git ./test/e2e
      - run:
          name: install dependency
          command: cd ./test/e2e && npm install
#      - run:
#          name: test
#          command: npm run test
